# Generated by Django 5.2.4 on 2025-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_jogador_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jogadores/'),
        ),
    ]
